CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_set` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`token`  varchar(255) NOT NULL  COMMENT ' Token ',
`keyword`  varchar(255) NOT NULL  COMMENT ' 关键词 ',
`intro`  text NOT NULL  COMMENT '封面简介',
`title`  varchar(255) NOT NULL  COMMENT '标题',
`cover`  int(10) UNSIGNED NOT NULL  COMMENT '封面图片',
`kfname`  varchar(255) NOT NULL  COMMENT '客服名称',
`TemplateIndex`  varchar(255) NOT NULL  DEFAULT 'default' COMMENT '模板编号',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_set','微餐饮-餐厅设置','0','','1','{"1":["keyword","title","cover","intro","kfname"]}','1:基础','','','','','id:编号\r\nkeyword:关键词\r\ntitle:标题\r\nid:操作:show&id=[id]|预览,listsedit&id=[id]|编辑,listsdel&id=[id]|删除','10','title','intro','1401103928','1401378396','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token',' Token ','varchar(255) NOT NULL','string','','','0','','0','0','1','1401108700','1401103980','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('keyword',' 关键词 ','varchar(255) NOT NULL','string','','','1','','0','1','1','1401108295','1401108295','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('intro','封面简介','text NOT NULL','textarea','','','1','','0','1','1','1401108377','1401108377','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','标题','varchar(255) NOT NULL','string','','','1','','0','1','1','1401108330','1401108330','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cover','封面图片','int(10) UNSIGNED NOT NULL','picture','','','1','','0','1','1','1401108403','1401108403','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('kfname','客服名称','varchar(255) NOT NULL','string','','用于评论中显示的回复名称','1','','0','0','1','1401118036','1401118036','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('TemplateIndex','模板编号','varchar(255) NOT NULL','string','default','使用的模板编号','0','','0','0','1','1401195917','1401195917','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_dishes` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`paixu`  int(10) NOT NULL  DEFAULT 0 COMMENT '排序',
`state`  tinyint(2) NOT NULL  DEFAULT 0 COMMENT '状态',
`review_count`  int(10) NOT NULL  DEFAULT 0 COMMENT '评论数量',
`icon`  int(10) UNSIGNED NOT NULL  COMMENT ' 菜品封面 ',
`dishes_num`  varchar(255) NOT NULL  COMMENT '菜品编号',
`price`  varchar(255) NOT NULL  COMMENT '价格',
`introduction`  text NOT NULL  COMMENT '菜品简介',
`name`  varchar(255) NOT NULL  COMMENT '菜品名称',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`youhuiid`  int(10) NOT NULL  DEFAULT 0 COMMENT '优惠id',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_dishes','微餐饮-菜品库','0','','1','{"1":["dishes_num","name","price","icon","introduction","order","state"]}','1:基础','','','','','id:编号\r\npaixu:排序号\r\nicon:15%菜品图片\r\nname:菜品名称\r\nstate|get_name_by_status:状态\r\nid:操作:[EDIT]&id=[id]|编辑,[DELETE]|删除','10','name','dishes_num','1401110349','1401541884','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('paixu','排序','int(10) NOT NULL','num','0','数字越大排序越靠前，默认按添加时间排序','1','','0','0','1','1401541928','1401120081','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('state','状态','tinyint(2) NOT NULL','bool','0','菜品下架后不会出现在菜单中','1','0:上架\r\n1:下架','0','0','1','1401203673','1401203673','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('review_count','评论数量','int(10) NOT NULL','num','0','','0','','0','0','1','1401111125','1401111125','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('icon',' 菜品封面 ','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1401202313','1401202313','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('dishes_num','菜品编号','varchar(255) NOT NULL','string','','','1','','0','1','1','1401110538','1401110538','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('price','价格','varchar(255) NOT NULL','string','','菜品的原价','1','','0','1','1','1401110913','1401110899','/^(d*.d{0,2}|d+).*$/','3','请输入正确的菜品价格','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('introduction','菜品简介','text NOT NULL','editor','','','1','','0','0','1','1401110665','1401110665','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','菜品名称','varchar(255) NOT NULL','string','','','1','','0','1','1','1401110494','1401110485','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1401201073','1401201073','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('youhuiid','优惠id','int(10) NOT NULL','num','0','表示该菜品属于那个优惠id','0','','0','0','1','1401693201','1401688829','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_scheduledtask` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`fenz`  varchar(255) NOT NULL  DEFAULT '*' COMMENT '每分',
`xiaos`  varchar(255) NOT NULL  DEFAULT '*' COMMENT '每时',
`yue`  varchar(255) NOT NULL  DEFAULT '*' COMMENT '每月',
`day`  varchar(255) NOT NULL  DEFAULT '*' COMMENT '每日',
`zhou`  varchar(255) NOT NULL  DEFAULT '*' COMMENT '每周',
`starttime_endtime`  text NOT NULL  COMMENT '开始和结束时间的序列化数据',
`state`  tinyint(2) NOT NULL  DEFAULT 0 COMMENT '状态',
`upruntime`  int(10) NOT NULL  COMMENT '上次执行时间',
`downruntime`  int(10) NOT NULL  COMMENT '下次任务执行时间',
`title`  text NOT NULL  COMMENT '任务名称',
`type`  int(10) NOT NULL  DEFAULT 0 COMMENT '任务类型',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_scheduledtask','微餐饮-计划任务列表','0','','1','{"1":["title","state","type","zhou","yue","day","xiaos","fenz"]}','1:基础','','','','','id:编号\r\ntitle:任务名称\r\nupruntime:上次执行时间\r\ndownruntime:下次执行时间','10','title','','1401112371','1401207461','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('fenz','每分','varchar(255) NOT NULL','string','*','设置哪一分钟执行本任务，多个值之间用半角逗号 "," 隔开，*”为不限制','1','','0','0','1','1401207395','1401207395','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('xiaos','每时','varchar(255) NOT NULL','string','*','设置哪一小时执行本任务，“*”为不限制','1','','0','0','1','1401207176','1401207176','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('yue','每月','varchar(255) NOT NULL','string','*','设置哪一月执行本任务，“*”为不限制','1','','0','0','1','1401207146','1401207010','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('day','每日','varchar(255) NOT NULL','string','*','设置哪一日执行本任务，“*”为不限制','1','','0','0','1','1401207130','1401207130','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('zhou','每周','varchar(255) NOT NULL','string','*','设置星期几执行本任务，“*”为不限制，本设置会覆盖下面的“日”设定','1','','0','0','1','1401206983','1401206983','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('starttime_endtime','开始和结束时间的序列化数据','text NOT NULL','textarea','','开始和结束时间的序列化数据','0','','0','0','1','1401112431','1401112431','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('state','状态','tinyint(2) NOT NULL','bool','0','停用后，计划任务将不会执行','1','0:启用\r\n1:停用','0','0','1','1401112617','1401112617','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('upruntime','上次执行时间','int(10) NOT NULL','datetime','','上次任务执行的时间','0','','0','0','1','1401112687','1401112687','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('downruntime','下次任务执行时间','int(10) NOT NULL','datetime','','下次任务执行的时间','0','','0','0','1','1401112735','1401112735','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','任务名称','text NOT NULL','textarea','','','1','','0','1','1','1401112503','1401112503','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('type','任务类型','int(10) NOT NULL','num','0','0:一次型,1:周期性,2:自定义时间','1','','0','0','1','1401206909','1401206909','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1401205393','1401205393','','3','','regex','get_token','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_tablemanage` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`ztnum`  varchar(255) NOT NULL  COMMENT '桌台编号',
`setid`  int(10) NOT NULL  COMMENT '餐厅id',
`paixu`  int(10) NOT NULL  DEFAULT 0 COMMENT '排序',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`ztdes`  text NOT NULL  COMMENT '餐位简介',
`state`  char(50) NOT NULL  DEFAULT 0 COMMENT '状态',
`yongccount`  int(10) NOT NULL  COMMENT '用餐人数',
`zttype`  varchar(255) NOT NULL  DEFAULT 0 COMMENT '餐位类型',
`ztname`  varchar(255) NOT NULL  COMMENT '餐位或包间名称',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_ml_microcatering_tablemanage` (`id`,`ztname`,`zttype`,`ztdes`,`yongccount`,`state`,`token`,`setid`,`ztnum`,`paixu`) VALUES ('5','国色甜香','1','<p>只有这个</p>','6','0','gh_3ee44a31f642','4','01','0');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_tablemanage','微餐饮-桌台（餐位）管理','0','','1','{"1":["ztnum","ztname","zttype","ztdes","yongccount","state","paixu"]}','1:基础','','','','','id:编号\r\nztnum:餐位编号\r\npaixu:排序号\r\nztname:餐位名称\r\nzttype|get_name_by_status:餐位类型\r\nyongccount:用餐人数\r\nstate|get_name_by_status:状态\r\nid:操作:[EDIT]&id=[id]|编辑,[DELETE]|删除','10','ztname','ztnum','1401112860','1401541512','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ztnum','桌台编号','varchar(255) NOT NULL','string','','','1','','0','0','1','1401118219','1401118219','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('setid','餐厅id','int(10) NOT NULL','num','','关联的餐厅id','0','','0','0','1','1401540887','1401205798','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('paixu','排序','int(10) NOT NULL','num','0','数字越大排序越靠前','1','','0','0','1','1401540899','1401205965','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1401205346','1401205346','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ztdes','餐位简介','text NOT NULL','editor','','','1','','0','0','1','1401118486','1401118486','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('state','状态','char(50) NOT NULL','select','0','','1','0:空闲\r\n1:已被预约\r\n2:维修中\r\n3:其他','0','0','1','1401540990','1401118861','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('yongccount','用餐人数','int(10) NOT NULL','num','','','1','','0','0','1','1401118515','1401118515','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('zttype','餐位类型','varchar(255) NOT NULL','select','0','','1','0:大厅\r\n1:包间','0','0','1','1401540934','1401118323','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ztname','餐位或包间名称','varchar(255) NOT NULL','string','','','1','','0','0','1','1401118448','1401118448','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_yuyuemanage` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`yycount`  int(10) NOT NULL  COMMENT '预约人数',
`sex`  int(10) NOT NULL  DEFAULT 0 COMMENT '预约人性别',
`usermobile`  varchar(255) NOT NULL  COMMENT '预约人电话',
`username`  varchar(255) NOT NULL  COMMENT '预约人姓名',
`openid`  varchar(255) NOT NULL  COMMENT '关联微信用户id',
`tablemanage_id`  int(10) NOT NULL  COMMENT '桌台编号',
`set_id`  int(10) NOT NULL  COMMENT '关联的餐厅编号',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_yuyuemanage','微餐饮-电话预约管理','0','','1','{"1":["username","usermobile","sex","yycount"]}','1:基础','','','','','id:编号\r\nusername:预约人姓名\r\nusermobile:预约人电话\r\nsex:性别\r\nyycount:预约人数','10','username','','1401113104','1401698416','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('yycount','预约人数','int(10) NOT NULL','num','','','1','','0','0','1','1401119030','1401119030','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sex','预约人性别','int(10) NOT NULL','num','0','0未知,1男,2女','1','','0','0','1','1401117511','1401117511','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('usermobile','预约人电话','varchar(255) NOT NULL','string','','','1','','0','0','1','1401117326','1401117326','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('username','预约人姓名','varchar(255) NOT NULL','string','','','1','','0','0','1','1401117300','1401117300','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','关联微信用户id','varchar(255) NOT NULL','string','','','0','','0','0','1','1401117271','1401117271','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('tablemanage_id','桌台编号','int(10) NOT NULL','num','','','0','','0','0','1','1401113324','1401113324','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('set_id','关联的餐厅编号','int(10) NOT NULL','num','','','0','','0','0','1','1401206543','1401206543','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_dishes_type` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`paixu`  int(10) NOT NULL  DEFAULT 0 COMMENT '排序',
`pic`  int(10) UNSIGNED NOT NULL  COMMENT '菜系图片',
`name`  varchar(255) NOT NULL  COMMENT '菜系名称',
`state`  tinyint(2) NOT NULL  DEFAULT 0 COMMENT '状态',
`setid`  int(10) NOT NULL  COMMENT '关联的餐厅id',
`dishesdatas`  text NOT NULL  COMMENT '菜品集合',
`introduction`  text NOT NULL  COMMENT '简介',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_ml_microcatering_dishes_type` (`id`,`token`,`state`,`introduction`,`name`,`pic`,`dishesdatas`,`setid`,`paixu`) VALUES ('91','gh_3ee44a31f642','0','<p>麻辣是特色</p>','川菜','372','N;','4','0');
INSERT INTO `wp_ml_microcatering_dishes_type` (`id`,`token`,`state`,`introduction`,`name`,`pic`,`dishesdatas`,`setid`,`paixu`) VALUES ('92','gh_3ee44a31f642','0','<p>清炖</p>','粤菜55','375','a:1:{i:0;s:2:"13";}','4','0');
INSERT INTO `wp_ml_microcatering_dishes_type` (`id`,`token`,`state`,`introduction`,`name`,`pic`,`dishesdatas`,`setid`,`paixu`) VALUES ('93','gh_3ee44a31f642','0','<p>麻辣是特色</p>','川菜','372','N;','5','0');
INSERT INTO `wp_ml_microcatering_dishes_type` (`id`,`token`,`state`,`introduction`,`name`,`pic`,`dishesdatas`,`setid`,`paixu`) VALUES ('94','gh_3ee44a31f642','0','<p>清炖</p>','粤菜22','375','a:1:{i:0;s:2:"13";}','5','0');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_dishes_type','微餐饮-菜系分类','0','','1','{"1":["name","pic","introduction","state","paixu"]}','1:基础','','','','','id:编号\r\npaixu:排序号\r\npic:15%菜系图片\r\nname:菜系名称\r\nstate|get_name_by_status:状态\r\nid:操作:[EDIT]&id=[id]&ctid=[setid]|编辑,[DELETE]|删除','10','name','introduction','1401113818','1401973013','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('paixu','排序','int(10) NOT NULL','num','0','数字越大,排序越靠前','1','','0','0','1','1401471365','1401471365','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pic','菜系图片','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1401113921','1401113921','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','菜系名称','varchar(255) NOT NULL','string','','','1','','0','1','1','1401113870','1401113870','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('state','状态','tinyint(2) NOT NULL','bool','0','停用后将不会显示在菜系栏目','1','0:启用\r\n1:停用','0','0','1','1401114031','1401114031','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('setid','关联的餐厅id','int(10) NOT NULL','num','','','0','','0','0','1','1401433017','1401433017','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('dishesdatas','菜品集合','text NOT NULL','textarea','','关联的菜品id集合序列化','0','','0','0','1','1401432947','1401432947','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('introduction','简介','text NOT NULL','editor','','','1','','0','0','1','1401113979','1401113979','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1401204630','1401204630','','3','','regex','get_token','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_review` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`plcontent`  text NOT NULL  COMMENT '评论内容',
`pltime`  int(10) NOT NULL  COMMENT '评论时间',
`hftime`  int(10) NOT NULL  COMMENT '回复时间',
`hfcontent`  text NOT NULL  COMMENT '回复内容',
`type`  int(10) NOT NULL  DEFAULT 0 COMMENT '评论类型',
`openid`  varchar(255) NOT NULL  COMMENT '关联的用户id',
`set_id`  int(10) NOT NULL  COMMENT '关联的餐厅id',
`dishes_id`  int(10) NOT NULL  COMMENT '关联的菜品id或者关联的桌台id',
`pingji`  int(10) NOT NULL  DEFAULT 3 COMMENT '菜品评级',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_review','微餐饮-评论','0','','1','{"1":["pltime","plcontent","hfcontent","hftime"]}','1:基础','','','','','id:编号\r\nopenid:评论用户id\r\npltime:评论时间','10','','','1401114177','1401206740','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('plcontent','评论内容','text NOT NULL','editor','','','1','','0','0','1','1401117765','1401117765','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pltime','评论时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1401117727','1401117727','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('hftime','回复时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1401117866','1401117866','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('hfcontent','回复内容','text NOT NULL','editor','','','1','','0','0','1','1401117839','1401117839','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('type','评论类型','int(10) NOT NULL','num','0','评论类型0菜品,1餐位','0','','0','0','1','1401115001','1401115001','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','关联的用户id','varchar(255) NOT NULL','string','','','0','','0','0','1','1401114232','1401114232','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('set_id','关联的餐厅id','int(10) NOT NULL','num','','','0','','0','0','1','1401114207','1401114207','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('dishes_id','关联的菜品id或者关联的桌台id','int(10) NOT NULL','num','','','0','','0','0','1','1401114340','1401114300','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pingji','菜品评级','int(10) NOT NULL','num','3','菜品的星级程度从1-5星','0','','0','0','1','1401114619','1401114619','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`tablemanage_id`  int(10) NOT NULL  COMMENT '关联的餐位编号',
`endtime`  varchar(255) NOT NULL  COMMENT '过期时间',
`zftype`  char(50) NOT NULL  DEFAULT 0 COMMENT '支付方式',
`price`  varchar(255) NOT NULL  COMMENT '点餐原总价',
`yhprice`  varchar(255) NOT NULL  COMMENT '优惠后的总价',
`openid`  varchar(255) NOT NULL  COMMENT '关联的微信用户id',
`dishes_count_datas`  text NOT NULL  COMMENT '点餐的菜品数量序列化数据',
`set_id`  int(10) NOT NULL  COMMENT '关联的餐厅id',
`statekz`  char(50) NOT NULL  DEFAULT 0 COMMENT '状态扩展',
`dcnum`  varchar(255) NOT NULL  COMMENT '点餐单号',
`state`  char(50) NOT NULL  DEFAULT 0 COMMENT '状态',
`diningtypes`  char(50) NOT NULL  DEFAULT 0 COMMENT '点餐类型',
`beizhu`  text NOT NULL  COMMENT '备注',
`cpcount`  int(10) NOT NULL  DEFAULT 0 COMMENT '菜品总数量',
`ctime`  varchar(255) NOT NULL  COMMENT '创建时间',
`jctime`  varchar(255) NOT NULL  COMMENT '就餐时间',
`contactid`  int(10) NOT NULL  COMMENT '关联的联系id',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_ml_microcatering_order` (`id`,`statekz`,`state`,`dcnum`,`set_id`,`dishes_count_datas`,`openid`,`price`,`yhprice`,`zftype`,`endtime`,`tablemanage_id`,`diningtypes`,`ctime`,`jctime`,`contactid`,`token`,`cpcount`,`beizhu`) VALUES ('14','0','0','2014060253531019','4','a:1:{i:13;a:12:{s:2:"id";s:2:"13";s:5:"token";s:15:"gh_3ee44a31f642";s:4:"name";s:9:"油辣子";s:10:"dishes_num";s:3:"001";s:4:"icon";s:3:"372";s:12:"introduction";s:16:"<p>非常霜</p>";s:5:"price";s:2:"17";s:12:"review_count";s:1:"0";s:5:"paixu";s:1:"0";s:5:"state";s:1:"0";s:8:"youhuiid";s:1:"0";s:3:"num";i:4;}}','owYXBjtoBtTAx_4hxSptaUTCawUQ','','68','0','14-06-09 18:02:29','5','1','14-06-02 18:02:29','2014-06-02 7:00:00','2','gh_3ee44a31f642','4','');
INSERT INTO `wp_ml_microcatering_order` (`id`,`statekz`,`state`,`dcnum`,`set_id`,`dishes_count_datas`,`openid`,`price`,`yhprice`,`zftype`,`endtime`,`tablemanage_id`,`diningtypes`,`ctime`,`jctime`,`contactid`,`token`,`cpcount`,`beizhu`) VALUES ('15','6','0','2014060897515151','4','a:1:{i:13;a:12:{s:2:"id";s:2:"13";s:5:"token";s:15:"gh_3ee44a31f642";s:4:"name";s:9:"油辣子";s:10:"dishes_num";s:3:"001";s:4:"icon";s:3:"372";s:12:"introduction";s:16:"<p>非常霜</p>";s:5:"price";s:2:"17";s:12:"review_count";s:1:"0";s:5:"paixu";s:1:"0";s:5:"state";s:1:"0";s:8:"youhuiid";s:1:"0";s:3:"num";i:14;}}','-1','','238','0','14-06-15 13:27:06','0','1','14-06-08 13:27:06','2014-06-08 3:00:00','3','gh_3ee44a31f642','14','');
INSERT INTO `wp_ml_microcatering_order` (`id`,`statekz`,`state`,`dcnum`,`set_id`,`dishes_count_datas`,`openid`,`price`,`yhprice`,`zftype`,`endtime`,`tablemanage_id`,`diningtypes`,`ctime`,`jctime`,`contactid`,`token`,`cpcount`,`beizhu`) VALUES ('16','0','0','2014060854484856','4','a:1:{i:13;a:12:{s:2:"id";s:2:"13";s:5:"token";s:15:"gh_3ee44a31f642";s:4:"name";s:9:"油辣子";s:10:"dishes_num";s:3:"001";s:4:"icon";s:3:"372";s:12:"introduction";s:16:"<p>非常霜</p>";s:5:"price";s:2:"17";s:12:"review_count";s:1:"0";s:5:"paixu";s:1:"0";s:5:"state";s:1:"0";s:8:"youhuiid";s:1:"0";s:3:"num";i:9;}}','-1','','153','0','14-06-15 14:54:46','5','0','14-06-08 14:54:46','2014-06-08 1:00:00','3','gh_3ee44a31f642','9','');
INSERT INTO `wp_ml_microcatering_order` (`id`,`statekz`,`state`,`dcnum`,`set_id`,`dishes_count_datas`,`openid`,`price`,`yhprice`,`zftype`,`endtime`,`tablemanage_id`,`diningtypes`,`ctime`,`jctime`,`contactid`,`token`,`cpcount`,`beizhu`) VALUES ('17','2','1','2014060856505410','4','a:1:{i:13;a:12:{s:2:"id";s:2:"13";s:5:"token";s:15:"gh_3ee44a31f642";s:4:"name";s:9:"油辣子";s:10:"dishes_num";s:3:"001";s:4:"icon";s:3:"372";s:12:"introduction";s:16:"<p>非常霜</p>";s:5:"price";s:2:"17";s:12:"review_count";s:1:"0";s:5:"paixu";s:1:"0";s:5:"state";s:1:"0";s:8:"youhuiid";s:1:"0";s:3:"num";i:9;}}','-1','','153','0','14-06-15 15:21:12','5','0','14-06-08 15:21:12','2014-06-08 1:00:00','3','gh_3ee44a31f642','9','');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_order','微餐饮-点餐管理','0','','1','{"1":["beizhu","jctime"]}','1:基础','','','','','id:编号\r\ndcnum:订单编号\r\nopenid:用户id\r\nctime:下单时间\r\njctime:就餐时间\r\nyhprice:优惠后总价\r\ncpcount:菜品数量\r\nstate|get_name_by_status:状态\r\nstatekz|get_name_by_status:附加状态\r\nbeizhu:备注\r\nid:操作:lookcp&ctid=[set_id]&id=[id]|查看详细,[EDIT]&id=[id]|修改订单状态','10','','','1401115120','1402217924','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('tablemanage_id','关联的餐位编号','int(10) NOT NULL','num','','','0','','0','0','1','1401116922','1401116922','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('endtime','过期时间','varchar(255) NOT NULL','string','','订单未支付过期时间','0','','0','0','1','1401699274','1401116798','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('zftype','支付方式','char(50) NOT NULL','select','0','','0','0:支付宝\r\n1:微信支付\r\n2:网银\r\n3:拉卡拉\r\n4:线下支付','0','0','1','1401636926','1401116261','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('price','点餐原总价','varchar(255) NOT NULL','string','','','0','','0','0','1','1401115978','1401115968','/^(d*.d{0,2}|d+).*$/','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('yhprice','优惠后的总价','varchar(255) NOT NULL','string','','','0','','0','0','1','1401116031','1401116031','/^(d*.d{0,2}|d+).*$/','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','关联的微信用户id','varchar(255) NOT NULL','string','','','0','','0','0','1','1401115609','1401115609','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('dishes_count_datas','点餐的菜品数量序列化数据','text NOT NULL','textarea','','','0','','0','0','1','1401115713','1401115713','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('set_id','关联的餐厅id','int(10) NOT NULL','num','','','0','','0','0','1','1401115308','1401115308','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('statekz','状态扩展','char(50) NOT NULL','select','0','','3','0:未支付\r\n1:已支付\r\n2:(未支付)申请取消订单\r\n3:(已支付)申请取消订单\r\n4:(已支付)退款中\r\n5:(已支付)拒绝申请取消订单\r\n6:已取消','0','0','1','1402220841','1401116657','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('dcnum','点餐单号','varchar(255) NOT NULL','string','','','0','','0','0','1','1401116387','1401116387','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('state','状态','char(50) NOT NULL','select','0','确认后的订单取消需要进入审核处理','3','0:未确认\r\n1:已确认','0','0','1','1402218290','1401116514','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('diningtypes','点餐类型','char(50) NOT NULL','select','0','','0','0:点餐\r\n1:预约\r\n2:外卖','0','0','1','1401637742','1401117110','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('beizhu','备注','text NOT NULL','textarea','','','1','','0','0','1','1401612088','1401612088','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cpcount','菜品总数量','int(10) NOT NULL','num','0','','0','','0','0','1','1401611560','1401611560','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','创建时间','varchar(255) NOT NULL','string','','订单创建时间','0','','0','0','1','1402216495','1401609275','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('jctime','就餐时间','varchar(255) NOT NULL','string','','用餐时间','1','','0','0','1','1401699089','1401609319','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('contactid','关联的联系id','int(10) NOT NULL','num','','联系信息id','0','','0','0','1','1401609458','1401609458','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1401610691','1401610691','','3','','regex','get_token','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_discount_type` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`ismain`  tinyint(2) NOT NULL  DEFAULT 0 COMMENT '是否为主要',
`name`  varchar(255) NOT NULL  COMMENT '优惠分类名称',
`state`  tinyint(2) NOT NULL  DEFAULT 0 COMMENT '状态',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`dishesdatas`  text NOT NULL  COMMENT '菜品id和优惠价格序列化数据',
`paixu`  int(10) NOT NULL  DEFAULT 0 COMMENT '排序',
`setid`  int(10) NOT NULL  COMMENT '餐厅id',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_discount_type','微餐饮-优惠分类','0','','1','{"1":["state","name","paixu"]}','1:基础','','','','','id:编号\r\npaixu:排序号\r\nname:菜系名称\r\nstate|get_name_by_status:状态\r\nismain|get_name_by_status:是否主要\r\nid:操作:setzhuyao&id=[id]&ctid=[setid]|设置为主要,[EDIT]&id=[id]]&ctid=[setid]|编辑,[DELETE]|删除','10','name','','1401119532','1401973037','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ismain','是否为主要','tinyint(2) NOT NULL','bool','0','设置为主要后,可以出现在菜品页面推荐','0','0:不是\r\n1:是','0','0','1','1401686835','1401686207','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','优惠分类名称','varchar(255) NOT NULL','string','','如特价，推荐，限时优惠，特供','1','','0','0','1','1401539832','1401119661','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('state','状态','tinyint(2) NOT NULL','bool','0','停用后将不会显示在优惠分类栏目中','1','0:启用\r\n1:停用','0','0','1','1401119857','1401119857','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1401205296','1401205296','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('dishesdatas','菜品id和优惠价格序列化数据','text NOT NULL','textarea','','','0','','0','0','1','1401539979','1401119705','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('paixu','排序','int(10) NOT NULL','num','0','数字越大排序越靠前，默认按添加时间排序','1','','0','0','1','1401539873','1401120018','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('setid','餐厅id','int(10) NOT NULL','num','','关联的餐厅id','0','','0','0','1','1401540169','1401539914','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_order_temp` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`setid`  int(10) NOT NULL  COMMENT '餐厅id',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`openid`  varchar(255) NOT NULL  COMMENT '用户id',
`cpid`  int(10) NOT NULL  COMMENT '菜品id',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_order_temp','微餐饮-订单临时表','0','','1','','1:基础','','','','','','10','','','1401610576','1401610576','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('setid','餐厅id','int(10) NOT NULL','num','','','0','','0','0','1','1401617668','1401617668','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1401610661','1401610661','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','用户id','varchar(255) NOT NULL','string','','','0','','0','0','1','1401610734','1401610734','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cpid','菜品id','int(10) NOT NULL','num','','关联的菜品id','0','','0','0','1','1401610839','1401610839','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_ml_microcatering_users` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`address`  varchar(555) NOT NULL  COMMENT '联系地址',
`truename`  varchar(255) NOT NULL  COMMENT '用户名称',
`tel`  varchar(255) NOT NULL  COMMENT '联系电话',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`openid`  varchar(255) NOT NULL  COMMENT '微信id',
`isdefault`  tinyint(2) NOT NULL  DEFAULT 0 COMMENT '是否默认',
`set_id`  int(10) NOT NULL  COMMENT '餐厅id',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_ml_microcatering_users` (`id`,`token`,`truename`,`tel`,`address`,`openid`,`isdefault`,`set_id`) VALUES ('1','gh_3ee44a31f642','张三','13400000000','123','-1','0','2');
INSERT INTO `wp_ml_microcatering_users` (`id`,`token`,`truename`,`tel`,`address`,`openid`,`isdefault`,`set_id`) VALUES ('2','gh_3ee44a31f642','张三','13438109388','特三个月','owYXBjtoBtTAx_4hxSptaUTCawUQ','0','4');
INSERT INTO `wp_ml_microcatering_users` (`id`,`token`,`truename`,`tel`,`address`,`openid`,`isdefault`,`set_id`) VALUES ('3','gh_3ee44a31f642','333','13400000000','123','-1','0','4');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('ml_microcatering_users','微餐饮-联系信息','0','','1','','1:基础','','','','','','10','','','1401694105','1401694105','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('address','联系地址','varchar(555) NOT NULL','string','','','1','','0','0','1','1401694266','1401694266','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('truename','用户名称','varchar(255) NOT NULL','string','','','1','','0','0','1','1401694187','1401694187','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('tel','联系电话','varchar(255) NOT NULL','string','','','1','','0','0','1','1401694239','1401694239','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1401694162','1401694162','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','微信id','varchar(255) NOT NULL','string','','','0','','0','0','1','1401694285','1401694285','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('isdefault','是否默认','tinyint(2) NOT NULL','bool','0','是否默认常用的地址','0','0:不是\r\n1:是','0','0','1','1401694451','1401694451','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('set_id','餐厅id','int(10) NOT NULL','num','','','0','','0','0','1','1401695024','1401695024','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
